# Generated by Django 3.2 on 2021-04-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_frizeri'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frizeri',
            new_name='Frizer',
        ),
        migrations.AlterModelOptions(
            name='frizer',
            options={'verbose_name_plural': 'Frizeri'},
        ),
    ]
