# Generated by Django 3.2 on 2021-04-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210413_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pachet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Pachete',
            },
        ),
    ]
