# Generated by Django 3.2 on 2021-04-15 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_produs'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='categorie',
            field=models.CharField(choices=[('Masini tuns', 'Masini tuns'), ('Masini contur', 'Masini contur'), ('Shavere', 'Shavere')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
