# Generated by Django 3.2 on 2021-04-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_produs_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='produs',
            name='categorie',
            field=models.CharField(choices=[('Masini tuns', 'masinituns'), ('Masini contur', 'masinicontur'), ('Shavere', 'shavere')], max_length=50),
        ),
    ]
