# Generated by Django 3.2 on 2021-04-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210415_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
