# Generated by Django 3.2 on 2021-04-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_produs_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='categorie',
            field=models.CharField(choices=[('Masini tuns', 'masini tuns'), ('Masini contur', 'masini contur'), ('Shavere', 'shavere')], max_length=50),
        ),
    ]
