# Generated by Django 3.2 on 2021-04-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_produs_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='categorie',
            field=models.CharField(choices=[('Masini tuns', 'Masini tuns'), ('Masini contur', 'Masini contur'), ('Shavere', 'Shavere')], max_length=50),
        ),
    ]
