# Generated by Django 3.2 on 2021-04-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_produs_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='categorie',
            field=models.CharField(choices=[('Masini tuns', 'masinituns'), ('Masini contur', 'masinicontur'), ('Shavere', 'shavere')], max_length=50),
        ),
    ]
