# Generated by Django 3.2 on 2021-04-20 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_produs_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='vizitate',
            field=models.CharField(choices=[('Masini tuns', 'masinituns'), ('Masini contur', 'masinicontur'), ('Shavere', 'shavere')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
