# Generated by Django 3.2 on 2021-04-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_produs_vizitate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='vizitate',
            field=models.CharField(choices=[('Cel mai vizitat', 'celmaivizitat')], max_length=50),
        ),
    ]
