# Generated by Django 3.2 on 2021-05-28 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='utilizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
