# Generated by Django 3.2 on 2021-06-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_cart_utilizator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='categorie',
            field=models.CharField(choices=[('Masini tuns', 'masinituns'), ('Masini contur', 'masinicontur'), ('Shavere', 'shavere'), ('Foarfece', 'foarfece')], max_length=50),
        ),
    ]
