# Generated by Django 3.2 on 2021-06-03 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_produs_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='frizer',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
