# Generated by Django 3.2 on 2021-06-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_frizer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='categorie',
            field=models.CharField(choices=[('Masini tuns', 'masinituns'), ('Masini contur', 'masinicontur'), ('Shavere', 'shavere'), ('Foarfece', 'foarfece'), ('Accesorii', 'accesorii')], max_length=50),
        ),
    ]
