# Generated by Django 3.1.4 on 2021-09-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_comanda_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='cart',
            field=models.ManyToManyField(blank=True, to='store.Produs'),
        ),
    ]
