# Generated by Django 3.1.4 on 2021-08-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210816_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
