# Generated by Django 3.1.4 on 2021-08-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('stat1', 'In asteptare'), ('stat2', 'Acceptat'), ('stat3', 'Refuzat')], default='stat1', max_length=40),
        ),
    ]
