# Generated by Django 3.1.4 on 2021-08-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
