# Generated by Django 3.2 on 2021-08-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_auto_20210817_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment',
            field=models.CharField(choices=[('12:00-13:00', '12:00-13:00'), ('13:00-14:00', '13:00-14:00'), ('14:00-15:00', '14:00-15:00'), ('15:00-16:00', '15:00-16:00'), ('16:00-17:00', '16:00-17:00'), ('17:00-18:00', '17:00-18:00')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.CharField(choices=[('Luni', 'Luni'), ('Marti', 'Marti '), ('Miercuri', 'Miercuri'), ('Joi', 'Joi'), ('Vineri', 'Vineri'), ('Sambata', 'Sambata'), ('Duminica', 'Duminica')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='frizer',
            field=models.CharField(choices=[('Claudiu', 'Claudiu'), ('Ivanciu', 'Ivanciu'), ('Gheorghe', 'Gheorghe')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pachet',
            field=models.CharField(choices=[('Tuns', 'Tuns'), ('Tuns + Barba', 'Tuns + Barba'), ('Tuns + Barba + Aranjat', 'Tuns + Barba + Aranjat'), ('Barba', 'Barba'), ('Vopsit barba', 'Vopsit barba'), ('Pensat', 'Pensat')], default=None, max_length=100),
        ),
    ]
