# Generated by Django 3.2 on 2021-08-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_auto_20210817_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('In asteptare', 'In asteptare'), ('Acceptat', 'Acceptat'), ('Refuzat', 'Refuzat')], default='In asteptare', max_length=40),
        ),
    ]
