# Generated by Django 3.1.4 on 2021-08-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_auto_20210824_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
