# Generated by Django 3.1.4 on 2021-08-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_auto_20210824_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment',
            field=models.CharField(choices=[('12_13', '12:00-13:00'), ('13_14', '13:00-14:00'), ('14_15', '14:00-15:00'), ('15_16', '15:00-16:00'), ('16_17', '16:00-17:00'), ('17_18', '17:00-18:00')], default='12_13', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.CharField(choices=[('Luni', 'Luni'), ('Marti', 'Marti'), ('Miercuri', 'Miercuri'), ('Joi', 'Joi'), ('Vineri', 'Vineri'), ('Sambata', 'Sambata'), ('Duminica', 'Duminica')], default='Luni', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='frizer',
            field=models.CharField(choices=[('Claudiu', 'Claudiu'), ('Ivanciu', 'Ivanciu'), ('Gheorghe', 'Gheorghe')], default='Claudiu', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pachet',
            field=models.CharField(choices=[('tuns', 'Tuns'), ('tuns_barba', 'Tuns + Barba'), ('tuns_barba_aranjat', 'Tuns + Barba + Aranjat'), ('babra', 'Barba'), ('vopsit_barba', 'Vopsit barba'), ('pensat', 'Pensat')], default='tuns', max_length=100),
        ),
    ]
