# Generated by Django 3.1.4 on 2021-08-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_auto_20210824_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created',
        ),
    ]
