# Generated by Django 3.1.4 on 2021-08-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_remove_appointment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment',
            field=models.CharField(choices=[('12:00-13:00', '12:00-13:00'), ('13:00-14:00', '13:00-14:00'), ('14:00-15:00', '14:00-15:00'), ('15:00-16:00', '15:00-16:00'), ('16:00-17:00', '16:00-17:00'), ('17:00-18:00', '17:00-18:00')], default='12:00-13:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.CharField(choices=[('Luni', 'Luni'), ('Marti', 'Marti'), ('Miercuri', 'Miercuri'), ('Joi', 'Joi'), ('Vineri', 'Vineri'), ('Sambata', 'Sambata')], default='Luni', max_length=100),
        ),
    ]
